import Head from "next/head";
//import Image from 'next/image'
//import AudioPlayer from "../components/AudioPlayer";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
    const [songlist, setSongList] = useState([]);
    //const [songlist2, setSongList2] = useState([]);
    const [currentSong, incCurrentSong] = useState(0);
    const [playStatus, setPlayStatus] = useState('PLAY');
    //const tracks = [{title:1}];

    useEffect(() => {
          function shuffle(a) {
            for (let i = a.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [a[i], a[j]] = [a[j], a[i]];
            }
            return a;
        }
        const getSongs = async (searchResults, index) => {
          const fetchResultDetails = await fetch(
            `https://archive.org/metadata/${searchResults[index].identifier}`
          );
          const resultDetails = await fetchResultDetails.json();
          console.log("search result:", resultDetails);

          const baseUrl = `https://${resultDetails.d1}${resultDetails.dir}/`;
          let mp3s = resultDetails.files
              .filter((f) => f.format === "VBR MP3" )
              .map((f) => ({
                  all: f,
                  url: baseUrl + f.name,
                  name: f.name.replace('.mp3', '')
                        .replaceAll('_', ' ')
                        .replace(/[^A-Za-z\s\-]/g, ''),
                  title: f.title,
                  length: f.length,
                  parent: 'https://archive.org/details/' + searchResults[index].identifier
              }));
          shuffle(mp3s);
          if(mp3s.length > 10){
              console.log(mp3s.length, 'trimming');
              mp3s = mp3s.slice(0, 10);
          }
          let combinedLength = songlist.length + mp3s.length;
          console.log("mp3", mp3s, combinedLength);
          setSongList(songlist => [...songlist, ...mp3s]);
          if(combinedLength < 10 && index < searchResults.length - 1){
            console.log('fetch more', combinedLength, searchResults.length - 1);
            getSongs(searchResults, ++index);
          }
        }

        const getData = async (url) => {
            const fetchApitResults = await fetch(url);
            const searchResults = await fetchApitResults.json();
            console.log("search results", searchResults.response.docs);
            getSongs(searchResults.response.docs, 0);
        };

        // getData('https://archive.org/advancedsearch.php?q=mediatype%3A%28audio%29+78rpm+jazz&fl%5B%5D=description&fl%5B%5D=identifier&fl%5B%5D=item_size&fl%5B%5D=mediatype&fl%5B%5D=name&fl%5B%5D=source&fl%5B%5D=title&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=5&page=1&output=json');
        let searchterm = 'tatum';
        let sorttype = ''; // '__random+asc';
        let rows = 10;
        getData(
            `https://archive.org/advancedsearch.php?q=mediatype%3A%28audio%29+78rpm+${searchterm}&fl%5B%5D=description&fl%5B%5D=identifier&fl%5B%5D=item_size&fl%5B%5D=mediatype&fl%5B%5D=name&fl%5B%5D=source&fl%5B%5D=title&sort%5B%5D=${sorttype}&sort%5B%5D=&sort%5B%5D=&rows=${rows}&page=1&output=json`
        );
    }, []);

    const handleEnd = () => {
        incCurrentSong(currentSong + 1);
    };

    let audioRef = null;

    const handlePlay = () => {
      let promise = audioRef.play();

      if (promise !== undefined) {
          promise.then(_ => {
              // Autoplay started!
          }).catch(error => {
            console.log('user to initiate play')
              // Autoplay was prevented.
              // Show a "Play" button so that user can start playback.
          });
      }
    };

    const handlePlayPause = () => {
        if(audioRef.paused){
          audioRef.play();
          setPlayStatus(playStatus => `PAUSE`);
        }else{
          audioRef.pause();
          setPlayStatus(playStatus => `PLAY`);
        }   
    }

    const handleNext = () => {
      incCurrentSong(currentSong + 1);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Gramaphone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet"></link>
            </Head>

            <main className={styles.main}>
                
                {songlist.length && (
                    <>         
                        <audio
                            src={songlist[currentSong].url}
                            ref={(input) => {
                                audioRef = input;
                            }}
                            controls
                            onEnded={handleEnd}
                            onCanPlay={handlePlay}
                        ></audio>
                        <div className={styles.songList + ' ' + styles.songListActive }>
                            <p >
                                {songlist[currentSong].name}
                            </p>
                            <p >
                                {songlist[currentSong].title}
                            </p>      
                        </div>
                        <div onClick={handlePlayPause}>{playStatus}</div>
                        <div onClick={handleNext}>skip</div>
                    </>
                )}
          </main>
        </div>
    );
}
